package vista;

import clases.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.modelEmpleado;

public class frmPrincipal extends javax.swing.JFrame {
    //Atributos
    CallCenter liquidacion = new CallCenter();
    modelEmpleado mdEmpleado = new modelEmpleado();
    Empleado empleado;
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelLiqNomina = new javax.swing.JPanel();
        jPanelConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonConsultarEmpleado = new javax.swing.JButton();
        jPanelInfoNomina = new javax.swing.JPanel();
        jPanelInfoEmpleado = new javax.swing.JPanel();
        jLabelInfoNomina = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelValorHoraExtra = new javax.swing.JLabel();
        jCheckBoxAuxTransporte = new javax.swing.JCheckBox();
        jTextFieldSalario = new javax.swing.JTextField();
        jTextValorHoraExtra = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonGenerarNomina = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTotalNomina = new javax.swing.JLabel();
        jTextField1Nomina = new javax.swing.JTextField();
        jLabelTotalPrestaciones = new javax.swing.JLabel();
        jTextFieldPrestaciones = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanelInfoNomina1 = new javax.swing.JPanel();
        jPanelInfoEmpleadoCrear = new javax.swing.JPanel();
        jLabelInfoNomina1 = new javax.swing.JLabel();
        jLabelSalario1 = new javax.swing.JLabel();
        jLabelValorHoraExtra1 = new javax.swing.JLabel();
        jCheckBoxAuxTransporte1 = new javax.swing.JCheckBox();
        jTextFieldSalario1 = new javax.swing.JTextField();
        jTextValorHoraExtra1 = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jButtonGuardarEmpleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelConsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Consultar Empleado");

        jLabelCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCodigo.setText("Codigo:");

        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jButtonConsultarEmpleado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonConsultarEmpleado.setText("Consultar Empleado");
        jButtonConsultarEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelConsultaLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabelCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelConsultaLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jButtonConsultarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelInfoNomina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelInfoEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelInfoNomina.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelInfoNomina.setForeground(new java.awt.Color(51, 51, 51));
        jLabelInfoNomina.setText("Información Nómina Empleado");

        jLabelSalario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSalario.setForeground(new java.awt.Color(51, 51, 51));
        jLabelSalario.setText("Salario:");

        jLabelValorHoraExtra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelValorHoraExtra.setForeground(new java.awt.Color(51, 51, 51));
        jLabelValorHoraExtra.setText("Valor Horas Extra:");

        jCheckBoxAuxTransporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBoxAuxTransporte.setText("Auxilio de Transporte");
        jCheckBoxAuxTransporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBoxAuxTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuxTransporteActionPerformed(evt);
            }
        });

        jTextFieldSalario.setEditable(false);
        jTextFieldSalario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSalario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextValorHoraExtra.setEditable(false);
        jTextValorHoraExtra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextValorHoraExtra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextValorHoraExtra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextValorHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorHoraExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleadoLayout = new javax.swing.GroupLayout(jPanelInfoEmpleado);
        jPanelInfoEmpleado.setLayout(jPanelInfoEmpleadoLayout);
        jPanelInfoEmpleadoLayout.setHorizontalGroup(
            jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAuxTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValorHoraExtra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSalario)
                            .addComponent(jTextValorHoraExtra))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInfoNomina)
                .addGap(35, 35, 35))
        );
        jPanelInfoEmpleadoLayout.setVerticalGroup(
            jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoNomina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorHoraExtra)
                    .addComponent(jTextValorHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuxTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelApellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelApellido.setText("Apellido:");

        jTextFieldApellido.setEditable(false);
        jTextFieldApellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonGenerarNomina.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGenerarNomina.setText("Generar Nómina");
        jButtonGenerarNomina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNominaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoNominaLayout = new javax.swing.GroupLayout(jPanelInfoNomina);
        jPanelInfoNomina.setLayout(jPanelInfoNominaLayout);
        jPanelInfoNominaLayout.setHorizontalGroup(
            jPanelInfoNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jTextFieldApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNominaLayout.createSequentialGroup()
                        .addComponent(jButtonGenerarNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelInfoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelInfoNominaLayout.setVerticalGroup(
            jPanelInfoNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNominaLayout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelInfoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerarNomina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTotalNomina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTotalNomina.setText("Total Nómina Empleado: ");

        jTextField1Nomina.setEditable(false);
        jTextField1Nomina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextField1Nomina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1Nomina.setText("0");
        jTextField1Nomina.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTotalPrestaciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTotalPrestaciones.setText("Total Prestaciones:");

        jTextFieldPrestaciones.setEditable(false);
        jTextFieldPrestaciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldPrestaciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPrestaciones.setText("0");
        jTextFieldPrestaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPrestaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrestacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalNomina)
                    .addComponent(jLabelTotalPrestaciones))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1Nomina)
                    .addComponent(jTextFieldPrestaciones))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalNomina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalPrestaciones)
                    .addComponent(jTextFieldPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanelLiqNominaLayout = new javax.swing.GroupLayout(jPanelLiqNomina);
        jPanelLiqNomina.setLayout(jPanelLiqNominaLayout);
        jPanelLiqNominaLayout.setHorizontalGroup(
            jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiqNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInfoNomina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLiqNominaLayout.setVerticalGroup(
            jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiqNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Liq Nomina", jPanelLiqNomina);

        jPanelInfoNomina1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelInfoEmpleadoCrear.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoEmpleadoCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelInfoNomina1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelInfoNomina1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelInfoNomina1.setText("Información Nómina Empleado");

        jLabelSalario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSalario1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelSalario1.setText("Salario:");

        jLabelValorHoraExtra1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelValorHoraExtra1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelValorHoraExtra1.setText("Valor Horas Extra:");

        jCheckBoxAuxTransporte1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBoxAuxTransporte1.setText("Auxilio de Transporte");
        jCheckBoxAuxTransporte1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBoxAuxTransporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuxTransporte1ActionPerformed(evt);
            }
        });

        jTextFieldSalario1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldSalario1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSalario1.setText("0");
        jTextFieldSalario1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextValorHoraExtra1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextValorHoraExtra1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextValorHoraExtra1.setText("0");
        jTextValorHoraExtra1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextValorHoraExtra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorHoraExtra1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleadoCrearLayout = new javax.swing.GroupLayout(jPanelInfoEmpleadoCrear);
        jPanelInfoEmpleadoCrear.setLayout(jPanelInfoEmpleadoCrearLayout);
        jPanelInfoEmpleadoCrearLayout.setHorizontalGroup(
            jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAuxTransporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                        .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValorHoraExtra1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSalario1)
                            .addComponent(jTextValorHoraExtra1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabelInfoNomina1)
                .addGap(35, 35, 35))
        );
        jPanelInfoEmpleadoCrearLayout.setVerticalGroup(
            jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoNomina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSalario1)
                    .addComponent(jTextFieldSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorHoraExtra1)
                    .addComponent(jTextValorHoraExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuxTransporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNombre1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre1.setText("Nombre:");

        jTextFieldNombre1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNombre1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelApellido1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelApellido1.setText("Apellido:");

        jTextFieldApellido1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldApellido1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonGuardarEmpleado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGuardarEmpleado.setText("Guardar");
        jButtonGuardarEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoNomina1Layout = new javax.swing.GroupLayout(jPanelInfoNomina1);
        jPanelInfoNomina1.setLayout(jPanelInfoNomina1Layout);
        jPanelInfoNomina1Layout.setHorizontalGroup(
            jPanelInfoNomina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNomina1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoNomina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre1)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jTextFieldApellido1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoNomina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNomina1Layout.createSequentialGroup()
                        .addComponent(jButtonGuardarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelInfoEmpleadoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelInfoNomina1Layout.setVerticalGroup(
            jPanelInfoNomina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNomina1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoNomina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNomina1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelApellido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelInfoEmpleadoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Registrar Empleado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInfoNomina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfoNomina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Empleado", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editar Empleado", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEmpleadoActionPerformed
        // TODO add your handling code here:
        
        empleado = mdEmpleado.consultaEmpleado(jTextFieldCodigo.getText());
        
        if (empleado == null) {
            JOptionPane.showMessageDialog(rootPane, "Empleado no existe");
            
            jTextFieldNombre.setText("");
            jTextFieldApellido.setText("");
            jTextFieldSalario.setText("");
            jTextValorHoraExtra.setText("");
            jTextFieldCodigo.setText("");
            jCheckBoxAuxTransporte.setSelected(false);
            
            jTextField1Nomina.setText("0");
            jTextFieldPrestaciones.setText("0"); 
        } else {
            jTextFieldNombre.setText(empleado.getNombre());
            jTextFieldApellido.setText(empleado.getApellido());
            jTextFieldSalario.setText(String.valueOf(empleado.getSalario()));
            jTextValorHoraExtra.setText(String.valueOf(empleado.getHorasExtra()));
            jCheckBoxAuxTransporte.setSelected(empleado.isAuxilioTransporte());
        }        
    }//GEN-LAST:event_jButtonConsultarEmpleadoActionPerformed

    private void jCheckBoxAuxTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuxTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAuxTransporteActionPerformed

    private void jTextValorHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorHoraExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorHoraExtraActionPerformed

    private void jButtonGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNominaActionPerformed
        // TODO add your handling code here:
        
        
        ArrayList<Double> nomina = new ArrayList<>();
        ArrayList<Double> prestacion = new ArrayList<>();
        empleado = mdEmpleado.consultaEmpleado(jTextFieldCodigo.getText());
        
        System.out.println("Liquidacion de Nominas: ");
        nomina = liquidacion.liquidarNominaEmp(empleado);
        
        for (int i = 0; i < nomina.size(); i++) {
            System.out.println(" Total a pagar: " + Math.round(nomina.get(i)));
            jTextField1Nomina.setText(String.valueOf(Math.round(nomina.get(i))));
            
        }
        System.out.println("Prestaciones Sociales");
        prestacion = liquidacion.liquidarPrestacionesEmp(empleado);
        
        for (int i = 0; i < prestacion.size(); i++) {
            System.out.format(" Total a pagar: %.2f", prestacion.get(i));
            jTextFieldPrestaciones.setText(String.valueOf(Math.round(prestacion.get(i))));
        } 
    }//GEN-LAST:event_jButtonGenerarNominaActionPerformed

    private void jTextFieldPrestacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrestacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrestacionesActionPerformed

    private void jCheckBoxAuxTransporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuxTransporte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAuxTransporte1ActionPerformed

    private void jTextValorHoraExtra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorHoraExtra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorHoraExtra1ActionPerformed

    private void jButtonGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEmpleadoActionPerformed
        // TODO add your handling code here:
        
        
        
        if(jTextFieldNombre1.getText().equals("") || jTextFieldApellido1.getText().equals("") || Integer.valueOf(jTextFieldSalario1.getText()) <= 0){
            
            JOptionPane.showMessageDialog(rootPane, "Los datos del nombre, apellido "
                                                    + "y salario son obligatorios");
        }else{
            if(mdEmpleado.crearEmpleado(jTextFieldNombre1.getText(), jTextFieldApellido1.getText(), Integer.valueOf(jTextValorHoraExtra1.getText()), jCheckBoxAuxTransporte1.isSelected(), Integer.valueOf(jTextFieldSalario1.getText()))){
                JOptionPane.showMessageDialog(rootPane, "Empleado guardado correctamente: \n" + jTextFieldNombre1.getText() + " " + jTextFieldApellido1.getText());
            }else{
                JOptionPane.showMessageDialog(rootPane, "Empleado NO guardado, intente nuevamente: \n" + jTextFieldNombre1.getText() + " " + jTextFieldApellido1.getText());
            }
        }
    }//GEN-LAST:event_jButtonGuardarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarEmpleado;
    private javax.swing.JButton jButtonGenerarNomina;
    private javax.swing.JButton jButtonGuardarEmpleado;
    private javax.swing.JCheckBox jCheckBoxAuxTransporte;
    private javax.swing.JCheckBox jCheckBoxAuxTransporte1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelInfoNomina;
    private javax.swing.JLabel jLabelInfoNomina1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSalario1;
    private javax.swing.JLabel jLabelTotalNomina;
    private javax.swing.JLabel jLabelTotalPrestaciones;
    private javax.swing.JLabel jLabelValorHoraExtra;
    private javax.swing.JLabel jLabelValorHoraExtra1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelInfoEmpleado;
    private javax.swing.JPanel jPanelInfoEmpleadoCrear;
    private javax.swing.JPanel jPanelInfoNomina;
    private javax.swing.JPanel jPanelInfoNomina1;
    private javax.swing.JPanel jPanelLiqNomina;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1Nomina;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldPrestaciones;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSalario1;
    private javax.swing.JTextField jTextValorHoraExtra;
    private javax.swing.JTextField jTextValorHoraExtra1;
    // End of variables declaration//GEN-END:variables
}
