/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Operaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author SENA CATA A205E07
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jTextFieldResultado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 204, 51));
        jLabelTitulo.setText("CALCULADORA BÁSICA");
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Número 1:");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabelResultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelResultado.setText(" RESULTADO");
        jLabelResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Número 2:");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));

        jTextFieldNumero1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldNumero2.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldResultado.setEditable(false);
        jTextFieldResultado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultado.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jTextFieldResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldResultado.setText("0");
        jTextFieldResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Suma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Resta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setText("Multiplicacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setText("Division");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Forma simplificada
        try {
                     
            Operaciones op = new Operaciones(Float.valueOf(jTextFieldNumero1.getText()), Float.valueOf(jTextFieldNumero2.getText())); //Creamos un instancia de la clase Operaciones
            jTextFieldResultado.setText(String.format("%.3f", op.resta())); // Atraves del setTex() le asignamos al componente el resultado y se muesta en la vista
        } catch(NumberFormatException e){ //manejo de exepcion
            jTextFieldNumero1.setText("");
            jTextFieldNumero2.setText("");
            JOptionPane.showMessageDialog(rootPane, "Error en los datos de entrada");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String a, b; //Se inicializan para poder asignarle los valores capturados por teclado (recordemos que son siempre de tipo String)
        float v1, v2; //Se inicializan para poder hacer la operacion aritmetica como float
        
        a = jTextFieldNumero1.getText(); //Asignamos a la variable A el valor capturado desde la vista
        b = jTextFieldNumero2.getText(); //Asignamos a la variable B el valor capturado desde la vista
        
        //Se genera try catch para controlar los errores en tiempo de ejecucion
        
        try{
            v1 = Float.valueOf(a); //Convertir datos numericos de String a float
            v2 = Float.valueOf(b); //Convertir datos numericos de String a float
            
            Operaciones op = new Operaciones(v1, v2); //Creamos un instancia de la clase Operaciones
            float resultado = op.multiplicacion(); //Invocamos el metodo (acorde para cada operacion de la clase Operaciones)
            String result = String.valueOf(resultado); //Convertimos a String el valor de la operacion para poder mostrarlo en la interfaz
            jTextFieldResultado.setText(String.format("%.3f", op.multiplicacion())); // Atraves del setTex() le asignamos al componente el resultado y se muesta en la vista
            
            //JOptionPane.showMessageDialog(rootPane, "El resultado es: " + (v1 * v2));
            
        }catch(NumberFormatException e){ //manejo de exepcion
            jTextFieldNumero1.setText("");
            jTextFieldNumero2.setText("");
            JOptionPane.showMessageDialog(rootPane, "Error en los daros de entrada");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String a, b; //Se inicializan para poder asignarle los valores capturados por teclado (recordemos que son siempre de tipo String)
        float v1, v2; //Se inicializan para poder hacer la operacion aritmetica como float
        
        a = jTextFieldNumero1.getText(); //Asignamos a la variable A el valor capturado desde la vista
        b = jTextFieldNumero2.getText(); //Asignamos a la variable B el valor capturado desde la vista
        
        //Se genera try catch para controlar los errores en tiempo de ejecucion
        try{
            
            v1 = Float.valueOf(a); //Convertir datos numericos de String a float
            v2 = Float.valueOf(b); //Convertir datos numericos de String a float
            
            Operaciones op = new Operaciones(v1, v2); //Creamos un instancia de la clase Operaciones
            //float resultado = op.suma(); //Invocamos el metodo (acorde para cada operacion de la clase Operaciones)
            //String result = String.valueOf(resultado); //Convertimos a String el valor de la operacion para poder mostrarlo en la interfaz
            jTextFieldResultado.setText(String.format("%.3f", op.suma())); // Atraves del setTex() le asignamos al componente el resultado y se muesta en la vista
            
            //JOptionPane.showMessageDialog(rootPane, "El resultado es: " + (v1 + v2));
            
            
            
        } catch (NumberFormatException e) { //manejo de exepcion
            jTextFieldNumero1.setText("");
            jTextFieldNumero2.setText("");
            JOptionPane.showMessageDialog(rootPane, "Error en los datos de entrada");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String a, b; //Se inicializan para poder asignarle los valores capturados por teclado (recordemos que son siempre de tipo String)
        float v1, v2; //Se inicializan para poder hacer la operacion aritmetica como float
        
        a = jTextFieldNumero1.getText(); //Asignamos a la variable A el valor capturado desde la vista
        b = jTextFieldNumero2.getText(); //Asignamos a la variable B el valor capturado desde la vista
        
        //Se genera try catch para controlar errores en tiempo de ejecucion
        try{
            v1 = Float.valueOf(a); //Convertir datos numericos de String a float
            v2 = Float.valueOf(b); //Convertir datos numericos de String a float
            
            Operaciones op = new Operaciones(v1, v2); //Creamos un instancia de la clase Operaciones
            //float resultado = op.division(); //Invocamos el metodo (acorde para cada operacion de la clase Operaciones)
            //String result = String.valueOf(resultado); //Convertimos a String el valor de la operacion para poder mostrarlo en la interfaz
            jTextFieldResultado.setText(String.format("%.3f", op.division())); // Atraves del setTex() le asignamos al componente el resultado y se muesta en la vista
            
            //JOptionPane.showMessageDialog(rootPane, "El resultado es: " + (v1 / v2));
            
        }catch(NumberFormatException e) { //manejo de exepcion
            jTextFieldNumero1.setText(a);
            jTextFieldNumero2.setText(b);
            JOptionPane.showMessageDialog(rootPane, "Error en los datos de entrada");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldNumero2;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
